spring.application.name=sistema-chamados

# Conexão com o banco
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_chamados
spring.datasource.username=postgres
spring.datasource.password=minato

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect